# Generated by Django 3.0.2 on 2020-01-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_transaction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_of_sell',
            field=models.DateTimeField(null=True),
        ),
    ]
