# Generated by Django 3.0.2 on 2020-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_transaction_date_of_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
    ]
