# Generated by Django 3.0.2 on 2020-02-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20200104_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
