# Generated by Django 3.0.2 on 2020-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20200203_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profit_usd',
            field=models.FloatField(null=True),
        ),
    ]
