# Generated by Django 3.0.2 on 2020-02-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20200207_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='profit_percentage',
            new_name='sell_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='profit_usd',
        ),
    ]
