# Generated by Django 3.0.2 on 2020-02-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20200207_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='purchase_price',
            new_name='buy_amount',
        ),
    ]
